### ISSUE TITLE
torch_normal not working as expected

### ISSUE THREAD

**Issue by Markus-Ewert** [mlverse/torch#421] opened 2020-12-28 10:39 UTC
Hi there, 

using the examples from the official documentations for the torch_normal functions, I obtain the following error message:

`torch_normal(2, 3, size=list(1, 4))`

Error: cpp_torch_namespace_normal_mean_Tensor_size_IntArrayRef does not exist
Run `rlang::last_error()` to see where the error occurred. 

Running the rlang::last_error() command yields the information that the function is not yet implemented:

> rlang::last_error()
<error/value_error>
cpp_torch_namespace_normal_mean_Tensor_size_IntArrayRef does not exist
Backtrace:
 1. torch::torch_normal(2, 3, size = list(1, 4))
 2. torch::.torch_normal(mean, std, size, generator) R/wrapers.R:101:2
 3. torch::call_c_function(...) R/gen-namespace.R:15622:0
 4. torch::value_error("{fun_name} does not exist") R/codegen-utils.R:259:2
Run `rlang::last_trace()` to see the full context.

The other examples from [this](https://torch.mlverse.org/docs/reference/torch_normal.html) page also do not work. 

Edit:
I currently use the following commands as a workaround:

`norm <- torch_ones_like(mu) * rnorm(mu$size())`

**Comment by dfalbel** [comment] 2020-12-28 12:02
Thanks for reporting! It's broken. I'll try to fix this early next week. If you are looking into generating random numbers with normal distribution, please look for the torch_randn function.

**Comment by krzjoa** [comment] 2021-01-22 17:13
I'm finishing the normal distribution implementation and I encountered exactly the same problem. I'll be able to carry on when it will be fixed. 😉

**Comment by dfalbel** [comment] 2021-01-22 21:49
OK! THe problem is that normal wasn't following any convention in the declarations.yaml file so we couldn't autogenerate the bindings. Let me try to fix this

**Comment by dfalbel** [comment] 2021-01-23 11:30
@Markus-Ewert , @krzjoa 

Should be fixed now in the dev version.

**Closed by dfalbel** 2021-01-23 11:30 UTC
