### ISSUE TITLE
torch::: autocomplete seems broken

### ISSUE THREAD

**Issue by Athospd** [mlverse/torch#1004] opened 2023-04-03 10:33 UTC
I found an issue regarding the autocomplete on RStudio when trying to list the torch functions under the ::: operator. It is hard to reproduce with reprex, but in summary, the following error appears when I press tab after torch::: in the console (and the function list does not appear at all).
```
> torch::: **(press TAB)**
Error: unexpected end of line in "torch:::"
Error in order(typeScores, scores) : argument lengths differ
In addition: Warning message:
In completions$type == .rs.acCompletionTypes$DATAFRAME & !completions$context %in%  :
  longer object length is not a multiple of shorter object length
```

---

``` r
sessionInfo()
#> R version 4.2.2 (2022-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8   
#> [3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
#> [5] LC_TIME=Portuguese_Brazil.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] digest_0.6.31   withr_2.5.0     lifecycle_1.0.3 reprex_2.0.2   
#>  [5] evaluate_0.20   rlang_1.0.6     cli_3.6.0       rstudioapi_0.14
#>  [9] fs_1.6.1        rmarkdown_2.20  tools_4.2.2     glue_1.6.2     
#> [13] xfun_0.37       yaml_2.3.7      fastmap_1.1.1   compiler_4.2.2 
#> [17] htmltools_0.5.4 knitr_1.42
```

``` r
RStudio.Version()
$citation

To cite RStudio in publications use:

  Posit team (2023). RStudio: Integrated Development Environment for R.
  Posit Software, PBC, Boston, MA. URL http://www.posit.co/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2023},
    url = {http://www.posit.co/},
  }


$mode
[1] "desktop"

$version
[1] ‘2023.3.0.386’

$long_version
[1] "2023.03.0+386"

$release_name
[1] "Cherry Blossom"
```

<sup>Created on 2023-04-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by shikokuchuo** [comment] 2023-05-31 11:44
Yes, just to confirm I also run into this issue latest torch and Rstudio.

```r
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS/LAPACK: /opt/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_rt.so.2;  LAPACK version 3.10.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/London
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] torch_0.10.0

loaded via a namespace (and not attached):
 [1] processx_3.8.1  bit_4.0.5       compiler_4.3.0  R6_2.5.1        magrittr_2.0.3  cli_3.6.1       tools_4.3.0    
 [8] rstudioapi_0.14 Rcpp_1.0.10     bit64_4.0.5     coro_1.0.3      callr_3.7.3     ps_1.7.5        rlang_1.1.1 
```
```r
> RStudio.Version()
$citation
To cite RStudio in publications use:

  Posit team (2023). RStudio: Integrated Development Environment for R. Posit Software, PBC, Boston, MA.
  URL http://www.posit.co/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {RStudio: Integrated Development Environment for R},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2023},
    url = {http://www.posit.co/},
  }

$mode
[1] "desktop"

$version
[1] ‘2023.3.1.446’

$long_version
[1] "2023.03.1+446"

$release_name
[1] "Cherry Blossom"
```

**Comment by dfalbel** [comment] 2023-05-31 13:26
I can reproduce too. Looks like:

```
.rs.rpc.get_completions("", list("torch"), list(5L), list(0L), 
                        "", "", list(), list(), FALSE, "", "", "torch:::", TRUE)
```

**Comment by dfalbel** [comment] 2023-06-06 07:17
I tracked it down to the same problem as: https://github.com/rstudio/rstudio/issues/13018
So this should be fixed in more recent RStudio versions.

**Closed by dfalbel** 2023-06-06 07:17 UTC
